Repository Yoyakso/comket-monorepo, pull requests merged in 2025-04, with the labels that each got.

#4 gradle 의존성 설정
  apps/backend/build.gradle
  apps/backend/src/main/java/kr/co/comket/backend/DemoApplication.java
  apps/backend/src/main/resources/application.yaml
Labels: 🧪 test, 🧹 chore

#5 RDS 연결 테스트
  .github/workflows/aws.yml
  .gitignore
  apps/backend/src/main/resources/application.yaml
Labels: 🧹 chore

#7 backend 브랜치 머지 - 프로젝트 환경 설정
  .github/workflows/aws.yml
  .gitignore
  apps/backend/src/main/resources/application.yaml
Labels: 🧹 chore

#8 Button, Badge 컴포넌트 구현
  .github/workflows/vercel-push.yml
  apps/frontend/src/assets/icons/.gitkeep
  apps/frontend/src/assets/icons/AddIcon.svg
  apps/frontend/src/assets/icons/DownArrowIcon.svg
  apps/frontend/src/components/.gitkeep
  apps/frontend/src/components/common/badge/Badge.Style.ts
  apps/frontend/src/components/common/badge/Badge.tsx
  apps/frontend/src/components/common/button/Button.Style.ts
  apps/frontend/src/components/common/button/Button.tsx
  apps/frontend/src/styles/theme.ts
Labels: 💄 ui, 🐣 yumin
